#
# Copyright (c) 2009      Cisco Systems, Inc.  All rights reserved. 
#
# $COPYRIGHT$
# 
# Additional copyrights may follow
# 
# $HEADER$
#

libopenrcm_la_SOURCES += \
        util/error_strings.c \
        util/triplets.h \
        util/triplets.c

